name: C/C++ CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup
      run: apt-get update && apt-get -y -qq install clang-tidy cppcheck
    - name: make
      run: make
      working-directory: ./libpvl
